// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PlataformaFutevolei.Infraestrutura.Persistencia;

#nullable disable

namespace PlataformaFutevolei.Infraestrutura.Persistencia.Migracoes
{
    [DbContext(typeof(PlataformaFutevoleiDbContext))]
    [Migration("20260324134129_AdicionarPerfisUsuariosEVinculos")]
    partial class AdicionarPerfisUsuariosEVinculos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PlataformaFutevolei.Dominio.Entidades.Atleta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Apelido")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("apelido");

                    b.Property<bool>("CadastroPendente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("cadastro_pendente");

                    b.Property<string>("Cpf")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cpf");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("date")
                        .HasColumnName("data_nascimento");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("Instagram")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("instagram");

                    b.Property<int>("Lado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3)
                        .HasColumnName("lado");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<string>("Telefone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("telefone");

                    b.HasKey("Id");

                    b.HasIndex("Cpf");

                    b.ToTable("atletas", (string)null);
                });

            modelBuilder.Entity("PlataformaFutevolei.Dominio.Entidades.CategoriaCompeticao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompeticaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("competicao_id");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<Guid?>("FormatoCampeonatoId")
                        .HasColumnType("uuid")
                        .HasColumnName("formato_campeonato_id");

                    b.Property<int>("Genero")
                        .HasColumnType("integer")
                        .HasColumnName("genero");

                    b.Property<int>("Nivel")
                        .HasColumnType("integer")
                        .HasColumnName("nivel");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<decimal>("PesoRanking")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasDefaultValue(1m)
                        .HasColumnName("peso_ranking");

                    b.HasKey("Id");

                    b.HasIndex("CompeticaoId");

                    b.HasIndex("FormatoCampeonatoId");

                    b.ToTable("categorias_competicao", (string)null);
                });

            modelBuilder.Entity("PlataformaFutevolei.Dominio.Entidades.Competicao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("ContaRankingLiga")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("conta_ranking_liga");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_fim");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_inicio");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("descricao");

                    b.Property<bool>("InscricoesAbertas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("inscricoes_abertas");

                    b.Property<Guid?>("LigaId")
                        .HasColumnType("uuid")
                        .HasColumnName("liga_id");

                    b.Property<Guid?>("LocalId")
                        .HasColumnType("uuid")
                        .HasColumnName("local_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<Guid?>("RegraCompeticaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("regra_competicao_id");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.Property<Guid?>("UsuarioOrganizadorId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_organizador_id");

                    b.HasKey("Id");

                    b.HasIndex("LigaId");

                    b.HasIndex("LocalId");

                    b.HasIndex("RegraCompeticaoId");

                    b.HasIndex("UsuarioOrganizadorId");

                    b.ToTable("competicoes", (string)null);
                });

            modelBuilder.Entity("PlataformaFutevolei.Dominio.Entidades.Dupla", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("Atleta1Id")
                        .HasColumnType("uuid")
                        .HasColumnName("atleta1_id");

                    b.Property<Guid>("Atleta2Id")
                        .HasColumnType("uuid")
                        .HasColumnName("atleta2_id");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex("Atleta1Id");

                    b.HasIndex("Atleta2Id");

                    b.HasIndex("Atleta1Id", "Atleta2Id")
                        .IsUnique();

                    b.ToTable("duplas", null, t =>
                        {
                            t.HasCheckConstraint("ck_duplas_atletas_diferentes", "\"atleta1_id\" <> \"atleta2_id\"");
                        });
                });

            modelBuilder.Entity("PlataformaFutevolei.Dominio.Entidades.FormatoCampeonato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<int?>("ClassificadosPorGrupo")
                        .HasColumnType("integer")
                        .HasColumnName("classificados_por_grupo");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("descricao");

                    b.Property<bool>("DisputaTerceiroLugar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("disputa_terceiro_lugar");

                    b.Property<bool>("GeraMataMataAposGrupos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("gera_mata_mata_apos_grupos");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<bool>("PermiteCabecaDeChave")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("permite_cabeca_de_chave");

                    b.Property<int?>("QuantidadeDerrotasParaEliminacao")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade_derrotas_para_eliminacao");

                    b.Property<int?>("QuantidadeGrupos")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade_grupos");

                    b.Property<string>("TipoChave")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tipo_chave");

                    b.Property<int>("TipoFormato")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_formato");

                    b.Property<bool>("TurnoEVolta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("turno_e_volta");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("formatos_campeonato", (string)null);
                });

            modelBuilder.Entity("PlataformaFutevolei.Dominio.Entidades.InscricaoCampeonato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CategoriaCompeticaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("categoria_competicao_id");

                    b.Property<Guid>("CompeticaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("competicao_id");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<DateTime>("DataInscricaoUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_inscricao_utc");

                    b.Property<Guid>("DuplaId")
                        .HasColumnType("uuid")
                        .HasColumnName("dupla_id");

                    b.Property<string>("Observacao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("observacao");

                    b.Property<bool>("Pago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("pago");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaCompeticaoId");

                    b.HasIndex("CompeticaoId");

                    b.HasIndex("DuplaId");

                    b.HasIndex("CategoriaCompeticaoId", "DuplaId")
                        .IsUnique();

                    b.ToTable("inscricoes_campeonato", (string)null);
                });

            modelBuilder.Entity("PlataformaFutevolei.Dominio.Entidades.Liga", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("ligas", (string)null);
                });

            modelBuilder.Entity("PlataformaFutevolei.Dominio.Entidades.Local", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<int>("QuantidadeQuadras")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade_quadras");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("locais", (string)null);
                });

            modelBuilder.Entity("PlataformaFutevolei.Dominio.Entidades.Partida", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CategoriaCompeticaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("categoria_competicao_id");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<DateTime?>("DataPartida")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_partida");

                    b.Property<Guid>("DuplaAId")
                        .HasColumnType("uuid")
                        .HasColumnName("dupla_a_id");

                    b.Property<Guid>("DuplaBId")
                        .HasColumnType("uuid")
                        .HasColumnName("dupla_b_id");

                    b.Property<Guid?>("DuplaVencedoraId")
                        .HasColumnType("uuid")
                        .HasColumnName("dupla_vencedora_id");

                    b.Property<string>("FaseCampeonato")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("fase_campeonato");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("observacoes");

                    b.Property<int>("PlacarDuplaA")
                        .HasColumnType("integer")
                        .HasColumnName("placar_dupla_a");

                    b.Property<int>("PlacarDuplaB")
                        .HasColumnType("integer")
                        .HasColumnName("placar_dupla_b");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaCompeticaoId");

                    b.HasIndex("DuplaAId");

                    b.HasIndex("DuplaBId");

                    b.HasIndex("DuplaVencedoraId");

                    b.HasIndex("CategoriaCompeticaoId", "DataPartida");

                    b.ToTable("partidas", null, t =>
                        {
                            t.HasCheckConstraint("ck_partidas_duplas_diferentes", "\"dupla_a_id\" <> \"dupla_b_id\"");

                            t.HasCheckConstraint("ck_partidas_placar_nao_negativo", "\"placar_dupla_a\" >= 0 AND \"placar_dupla_b\" >= 0");

                            t.HasCheckConstraint("ck_partidas_status_e_resultado", "((\"status\" = 1) AND \"dupla_vencedora_id\" IS NULL AND \"placar_dupla_a\" = 0 AND \"placar_dupla_b\" = 0) OR ((\"status\" = 2) AND (((\"placar_dupla_a\" = \"placar_dupla_b\") AND \"dupla_vencedora_id\" IS NULL) OR ((\"placar_dupla_a\" > \"placar_dupla_b\") AND \"dupla_vencedora_id\" = \"dupla_a_id\") OR ((\"placar_dupla_b\" > \"placar_dupla_a\") AND \"dupla_vencedora_id\" = \"dupla_b_id\")))");

                            t.HasCheckConstraint("ck_partidas_vencedora_valida", "\"dupla_vencedora_id\" IS NULL OR \"dupla_vencedora_id\" = \"dupla_a_id\" OR \"dupla_vencedora_id\" = \"dupla_b_id\"");
                        });
                });

            modelBuilder.Entity("PlataformaFutevolei.Dominio.Entidades.RegraCompeticao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("descricao");

                    b.Property<int>("DiferencaMinimaPartida")
                        .HasColumnType("integer")
                        .HasColumnName("diferenca_minima_partida");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<bool>("PermiteEmpate")
                        .HasColumnType("boolean")
                        .HasColumnName("permite_empate");

                    b.Property<decimal>("PontosDerrota")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("pontos_derrota");

                    b.Property<int>("PontosMinimosPartida")
                        .HasColumnType("integer")
                        .HasColumnName("pontos_minimos_partida");

                    b.Property<decimal>("PontosParticipacao")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("pontos_participacao");

                    b.Property<decimal>("PontosPrimeiroLugar")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("pontos_primeiro_lugar");

                    b.Property<decimal>("PontosSegundoLugar")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("pontos_segundo_lugar");

                    b.Property<decimal>("PontosTerceiroLugar")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("pontos_terceiro_lugar");

                    b.Property<decimal>("PontosVitoria")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("pontos_vitoria");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("regras_competicao", (string)null);
                });

            modelBuilder.Entity("PlataformaFutevolei.Dominio.Entidades.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<Guid?>("AtletaId")
                        .HasColumnType("uuid")
                        .HasColumnName("atleta_id");

                    b.Property<DateTime?>("CodigoRedefinicaoSenhaExpiraEmUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("codigo_redefinicao_senha_expira_em_utc");

                    b.Property<string>("CodigoRedefinicaoSenhaHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("codigo_redefinicao_senha_hash");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<int>("Perfil")
                        .HasColumnType("integer")
                        .HasColumnName("perfil");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("senha_hash");

                    b.HasKey("Id");

                    b.HasIndex("AtletaId")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("PlataformaFutevolei.Dominio.Entidades.CategoriaCompeticao", b =>
                {
                    b.HasOne("PlataformaFutevolei.Dominio.Entidades.Competicao", "Competicao")
                        .WithMany("Categorias")
                        .HasForeignKey("CompeticaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlataformaFutevolei.Dominio.Entidades.FormatoCampeonato", "FormatoCampeonato")
                        .WithMany()
                        .HasForeignKey("FormatoCampeonatoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Competicao");

                    b.Navigation("FormatoCampeonato");
                });

            modelBuilder.Entity("PlataformaFutevolei.Dominio.Entidades.Competicao", b =>
                {
                    b.HasOne("PlataformaFutevolei.Dominio.Entidades.Liga", "Liga")
                        .WithMany("Competicoes")
                        .HasForeignKey("LigaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PlataformaFutevolei.Dominio.Entidades.Local", "Local")
                        .WithMany("Competicoes")
                        .HasForeignKey("LocalId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PlataformaFutevolei.Dominio.Entidades.RegraCompeticao", "RegraCompeticao")
                        .WithMany("Competicoes")
                        .HasForeignKey("RegraCompeticaoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PlataformaFutevolei.Dominio.Entidades.Usuario", "UsuarioOrganizador")
                        .WithMany()
                        .HasForeignKey("UsuarioOrganizadorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Liga");

                    b.Navigation("Local");

                    b.Navigation("RegraCompeticao");

                    b.Navigation("UsuarioOrganizador");
                });

            modelBuilder.Entity("PlataformaFutevolei.Dominio.Entidades.Dupla", b =>
                {
                    b.HasOne("PlataformaFutevolei.Dominio.Entidades.Atleta", "Atleta1")
                        .WithMany("DuplasComoAtleta1")
                        .HasForeignKey("Atleta1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PlataformaFutevolei.Dominio.Entidades.Atleta", "Atleta2")
                        .WithMany("DuplasComoAtleta2")
                        .HasForeignKey("Atleta2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Atleta1");

                    b.Navigation("Atleta2");
                });

            modelBuilder.Entity("PlataformaFutevolei.Dominio.Entidades.InscricaoCampeonato", b =>
                {
                    b.HasOne("PlataformaFutevolei.Dominio.Entidades.CategoriaCompeticao", "CategoriaCompeticao")
                        .WithMany("Inscricoes")
                        .HasForeignKey("CategoriaCompeticaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlataformaFutevolei.Dominio.Entidades.Competicao", "Competicao")
                        .WithMany("Inscricoes")
                        .HasForeignKey("CompeticaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlataformaFutevolei.Dominio.Entidades.Dupla", "Dupla")
                        .WithMany()
                        .HasForeignKey("DuplaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CategoriaCompeticao");

                    b.Navigation("Competicao");

                    b.Navigation("Dupla");
                });

            modelBuilder.Entity("PlataformaFutevolei.Dominio.Entidades.Partida", b =>
                {
                    b.HasOne("PlataformaFutevolei.Dominio.Entidades.CategoriaCompeticao", "CategoriaCompeticao")
                        .WithMany("Partidas")
                        .HasForeignKey("CategoriaCompeticaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlataformaFutevolei.Dominio.Entidades.Dupla", "DuplaA")
                        .WithMany("PartidasComoDuplaA")
                        .HasForeignKey("DuplaAId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PlataformaFutevolei.Dominio.Entidades.Dupla", "DuplaB")
                        .WithMany("PartidasComoDuplaB")
                        .HasForeignKey("DuplaBId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PlataformaFutevolei.Dominio.Entidades.Dupla", "DuplaVencedora")
                        .WithMany("PartidasVencidas")
                        .HasForeignKey("DuplaVencedoraId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CategoriaCompeticao");

                    b.Navigation("DuplaA");

                    b.Navigation("DuplaB");

                    b.Navigation("DuplaVencedora");
                });

            modelBuilder.Entity("PlataformaFutevolei.Dominio.Entidades.Usuario", b =>
                {
                    b.HasOne("PlataformaFutevolei.Dominio.Entidades.Atleta", "Atleta")
                        .WithOne("Usuario")
                        .HasForeignKey("PlataformaFutevolei.Dominio.Entidades.Usuario", "AtletaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Atleta");
                });

            modelBuilder.Entity("PlataformaFutevolei.Dominio.Entidades.Atleta", b =>
                {
                    b.Navigation("DuplasComoAtleta1");

                    b.Navigation("DuplasComoAtleta2");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PlataformaFutevolei.Dominio.Entidades.CategoriaCompeticao", b =>
                {
                    b.Navigation("Inscricoes");

                    b.Navigation("Partidas");
                });

            modelBuilder.Entity("PlataformaFutevolei.Dominio.Entidades.Competicao", b =>
                {
                    b.Navigation("Categorias");

                    b.Navigation("Inscricoes");
                });

            modelBuilder.Entity("PlataformaFutevolei.Dominio.Entidades.Dupla", b =>
                {
                    b.Navigation("PartidasComoDuplaA");

                    b.Navigation("PartidasComoDuplaB");

                    b.Navigation("PartidasVencidas");
                });

            modelBuilder.Entity("PlataformaFutevolei.Dominio.Entidades.Liga", b =>
                {
                    b.Navigation("Competicoes");
                });

            modelBuilder.Entity("PlataformaFutevolei.Dominio.Entidades.Local", b =>
                {
                    b.Navigation("Competicoes");
                });

            modelBuilder.Entity("PlataformaFutevolei.Dominio.Entidades.RegraCompeticao", b =>
                {
                    b.Navigation("Competicoes");
                });
#pragma warning restore 612, 618
        }
    }
}
