// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PlataformaFutevolei.Infraestrutura.Persistencia;

#nullable disable

namespace PlataformaFutevolei.Infraestrutura.Persistencia.Migracoes
{
    [DbContext(typeof(PlataformaFutevoleiDbContext))]
    [Migration("20260310191611_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PlataformaFutevolei.Dominio.Entidades.Atleta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Apelido")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("apelido");

                    b.Property<string>("Cidade")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cidade");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.ToTable("atletas", (string)null);
                });

            modelBuilder.Entity("PlataformaFutevolei.Dominio.Entidades.CategoriaCompeticao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompeticaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("competicao_id");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<int>("Genero")
                        .HasColumnType("integer")
                        .HasColumnName("genero");

                    b.Property<int>("Nivel")
                        .HasColumnType("integer")
                        .HasColumnName("nivel");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex("CompeticaoId");

                    b.ToTable("categorias_competicao", (string)null);
                });

            modelBuilder.Entity("PlataformaFutevolei.Dominio.Entidades.Competicao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_fim");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_inicio");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.ToTable("competicoes", (string)null);
                });

            modelBuilder.Entity("PlataformaFutevolei.Dominio.Entidades.Dupla", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("Atleta1Id")
                        .HasColumnType("uuid")
                        .HasColumnName("atleta1_id");

                    b.Property<Guid>("Atleta2Id")
                        .HasColumnType("uuid")
                        .HasColumnName("atleta2_id");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex("Atleta1Id");

                    b.HasIndex("Atleta2Id");

                    b.HasIndex("Atleta1Id", "Atleta2Id")
                        .IsUnique();

                    b.ToTable("duplas", null, t =>
                        {
                            t.HasCheckConstraint("ck_duplas_atletas_diferentes", "\"atleta1_id\" <> \"atleta2_id\"");
                        });
                });

            modelBuilder.Entity("PlataformaFutevolei.Dominio.Entidades.Partida", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CategoriaCompeticaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("categoria_competicao_id");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<DateTime>("DataPartida")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_partida");

                    b.Property<Guid>("DuplaAId")
                        .HasColumnType("uuid")
                        .HasColumnName("dupla_a_id");

                    b.Property<Guid>("DuplaBId")
                        .HasColumnType("uuid")
                        .HasColumnName("dupla_b_id");

                    b.Property<Guid>("DuplaVencedoraId")
                        .HasColumnType("uuid")
                        .HasColumnName("dupla_vencedora_id");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("observacoes");

                    b.Property<int>("PlacarDuplaA")
                        .HasColumnType("integer")
                        .HasColumnName("placar_dupla_a");

                    b.Property<int>("PlacarDuplaB")
                        .HasColumnType("integer")
                        .HasColumnName("placar_dupla_b");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaCompeticaoId");

                    b.HasIndex("DuplaAId");

                    b.HasIndex("DuplaBId");

                    b.HasIndex("DuplaVencedoraId");

                    b.ToTable("partidas", null, t =>
                        {
                            t.HasCheckConstraint("ck_partidas_duplas_diferentes", "\"dupla_a_id\" <> \"dupla_b_id\"");

                            t.HasCheckConstraint("ck_partidas_vencedora_valida", "\"dupla_vencedora_id\" = \"dupla_a_id\" OR \"dupla_vencedora_id\" = \"dupla_b_id\"");
                        });
                });

            modelBuilder.Entity("PlataformaFutevolei.Dominio.Entidades.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<int>("Perfil")
                        .HasColumnType("integer")
                        .HasColumnName("perfil");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("senha_hash");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("PlataformaFutevolei.Dominio.Entidades.CategoriaCompeticao", b =>
                {
                    b.HasOne("PlataformaFutevolei.Dominio.Entidades.Competicao", "Competicao")
                        .WithMany("Categorias")
                        .HasForeignKey("CompeticaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competicao");
                });

            modelBuilder.Entity("PlataformaFutevolei.Dominio.Entidades.Dupla", b =>
                {
                    b.HasOne("PlataformaFutevolei.Dominio.Entidades.Atleta", "Atleta1")
                        .WithMany("DuplasComoAtleta1")
                        .HasForeignKey("Atleta1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PlataformaFutevolei.Dominio.Entidades.Atleta", "Atleta2")
                        .WithMany("DuplasComoAtleta2")
                        .HasForeignKey("Atleta2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Atleta1");

                    b.Navigation("Atleta2");
                });

            modelBuilder.Entity("PlataformaFutevolei.Dominio.Entidades.Partida", b =>
                {
                    b.HasOne("PlataformaFutevolei.Dominio.Entidades.CategoriaCompeticao", "CategoriaCompeticao")
                        .WithMany("Partidas")
                        .HasForeignKey("CategoriaCompeticaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlataformaFutevolei.Dominio.Entidades.Dupla", "DuplaA")
                        .WithMany("PartidasComoDuplaA")
                        .HasForeignKey("DuplaAId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PlataformaFutevolei.Dominio.Entidades.Dupla", "DuplaB")
                        .WithMany("PartidasComoDuplaB")
                        .HasForeignKey("DuplaBId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PlataformaFutevolei.Dominio.Entidades.Dupla", "DuplaVencedora")
                        .WithMany("PartidasVencidas")
                        .HasForeignKey("DuplaVencedoraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CategoriaCompeticao");

                    b.Navigation("DuplaA");

                    b.Navigation("DuplaB");

                    b.Navigation("DuplaVencedora");
                });

            modelBuilder.Entity("PlataformaFutevolei.Dominio.Entidades.Atleta", b =>
                {
                    b.Navigation("DuplasComoAtleta1");

                    b.Navigation("DuplasComoAtleta2");
                });

            modelBuilder.Entity("PlataformaFutevolei.Dominio.Entidades.CategoriaCompeticao", b =>
                {
                    b.Navigation("Partidas");
                });

            modelBuilder.Entity("PlataformaFutevolei.Dominio.Entidades.Competicao", b =>
                {
                    b.Navigation("Categorias");
                });

            modelBuilder.Entity("PlataformaFutevolei.Dominio.Entidades.Dupla", b =>
                {
                    b.Navigation("PartidasComoDuplaA");

                    b.Navigation("PartidasComoDuplaB");

                    b.Navigation("PartidasVencidas");
                });
#pragma warning restore 612, 618
        }
    }
}
