// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PlataformaFutevolei.Infraestrutura.Persistencia;

#nullable disable

namespace PlataformaFutevolei.Infraestrutura.Persistencia.Migracoes
{
    [DbContext(typeof(PlataformaFutevoleiDbContext))]
    partial class PlataformaFutevoleiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PlataformaFutevolei.Dominio.Entidades.Atleta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Apelido")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("apelido");

                    b.Property<bool>("CadastroPendente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("cadastro_pendente");

                    b.Property<string>("Bairro")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("bairro");

                    b.Property<string>("Cidade")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("cidade");

                    b.Property<string>("Cpf")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cpf");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("date")
                        .HasColumnName("data_nascimento");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("Estado")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("estado");

                    b.Property<string>("Instagram")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("instagram");

                    b.Property<int>("Lado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3)
                        .HasColumnName("lado");

                    b.Property<int?>("Nivel")
                        .HasColumnType("integer")
                        .HasColumnName("nivel");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<string>("Telefone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("telefone");

                    b.HasKey("Id");

                    b.HasIndex("Cpf");

                    b.ToTable("atletas", (string)null);
                });

            modelBuilder.Entity("PlataformaFutevolei.Dominio.Entidades.CategoriaCompeticao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompeticaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("competicao_id");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<Guid?>("FormatoCampeonatoId")
                        .HasColumnType("uuid")
                        .HasColumnName("formato_campeonato_id");

                    b.Property<int>("Genero")
                        .HasColumnType("integer")
                        .HasColumnName("genero");

                    b.Property<bool>("InscricoesEncerradas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("inscricoes_encerradas");

                    b.Property<int>("Nivel")
                        .HasColumnType("integer")
                        .HasColumnName("nivel");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<decimal>("PesoRanking")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasDefaultValue(1m)
                        .HasColumnName("peso_ranking");

                    b.Property<int?>("QuantidadeMaximaDuplas")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade_maxima_duplas");

                    b.Property<DateTime?>("TabelaJogosAprovadaEmUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tabela_jogos_aprovada_em_utc");

                    b.Property<Guid?>("TabelaJogosAprovadaPorUsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("tabela_jogos_aprovada_por_usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("CompeticaoId");

                    b.HasIndex("FormatoCampeonatoId");

                    b.HasIndex("TabelaJogosAprovadaPorUsuarioId");

                    b.ToTable("categorias_competicao", (string)null);
                });

            modelBuilder.Entity("PlataformaFutevolei.Dominio.Entidades.Competicao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("ContaRankingLiga")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("conta_ranking_liga");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_fim");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_inicio");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("descricao");

                    b.Property<Guid?>("FormatoCampeonatoId")
                        .HasColumnType("uuid")
                        .HasColumnName("formato_campeonato_id");

                    b.Property<bool>("InscricoesAbertas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("inscricoes_abertas");

                    b.Property<Guid?>("LigaId")
                        .HasColumnType("uuid")
                        .HasColumnName("liga_id");

                    b.Property<string>("Link")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("link");

                    b.Property<Guid?>("LocalId")
                        .HasColumnType("uuid")
                        .HasColumnName("local_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<bool>("PossuiFinalReset")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("possui_final_reset");

                    b.Property<Guid?>("RegraCompeticaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("regra_competicao_id");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.Property<Guid?>("UsuarioOrganizadorId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_organizador_id");

                    b.HasKey("Id");

                    b.HasIndex("FormatoCampeonatoId");

                    b.HasIndex("LigaId");

                    b.HasIndex("LocalId");

                    b.HasIndex("RegraCompeticaoId");

                    b.HasIndex("UsuarioOrganizadorId");

                    b.ToTable("competicoes", (string)null);
                });

            modelBuilder.Entity("PlataformaFutevolei.Dominio.Entidades.ConviteCadastro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("CanalEnvio")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("canal_envio");

                    b.Property<string>("CodigoConviteHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("codigo_convite_hash");

                    b.Property<string>("CodigoConvite")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("codigo_convite");

                    b.Property<Guid>("CriadoPorUsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("criado_por_usuario_id");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("EmailEnviadoEmUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_enviado_em_utc");

                    b.Property<string>("ErroEnvioEmail")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("erro_envio_email");

                    b.Property<string>("ErroEnvioWhatsapp")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("erro_envio_whatsapp");

                    b.Property<DateTime>("ExpiraEmUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expira_em_utc");

                    b.Property<string>("IdentificadorPublico")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("identificador_publico");

                    b.Property<int>("PerfilDestino")
                        .HasColumnType("integer")
                        .HasColumnName("perfil_destino");

                    b.Property<string>("Telefone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("telefone");

                    b.Property<DateTime?>("UltimaTentativaEnvioEmailEmUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultima_tentativa_envio_email_em_utc");

                    b.Property<DateTime?>("UltimaTentativaEnvioWhatsappEmUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultima_tentativa_envio_whatsapp_em_utc");

                    b.Property<DateTime?>("UsadoEmUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("usado_em_utc");

                    b.Property<DateTime?>("WhatsappEnviadoEmUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("whatsapp_enviado_em_utc");

                    b.HasKey("Id");

                    b.HasIndex("CriadoPorUsuarioId");

                    b.HasIndex("Email");

                    b.HasIndex("IdentificadorPublico")
                        .IsUnique();

                    b.HasIndex("Ativo", "ExpiraEmUtc");

                    b.ToTable("convites_cadastro", (string)null);
                });

            modelBuilder.Entity("PlataformaFutevolei.Dominio.Entidades.Dupla", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("Atleta1Id")
                        .HasColumnType("uuid")
                        .HasColumnName("atleta1_id");

                    b.Property<Guid>("Atleta2Id")
                        .HasColumnType("uuid")
                        .HasColumnName("atleta2_id");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex("Atleta1Id");

                    b.HasIndex("Atleta2Id");

                    b.HasIndex("Atleta1Id", "Atleta2Id")
                        .IsUnique();

                    b.ToTable("duplas", null, t =>
                        {
                            t.HasCheckConstraint("ck_duplas_atletas_diferentes", "\"atleta1_id\" <> \"atleta2_id\"");
                        });
                });

            modelBuilder.Entity("PlataformaFutevolei.Dominio.Entidades.FormatoCampeonato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<int?>("ClassificadosPorGrupo")
                        .HasColumnType("integer")
                        .HasColumnName("classificados_por_grupo");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("descricao");

                    b.Property<bool>("DisputaTerceiroLugar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("disputa_terceiro_lugar");

                    b.Property<bool>("GeraMataMataAposGrupos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("gera_mata_mata_apos_grupos");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<bool>("PermiteCabecaDeChave")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("permite_cabeca_de_chave");

                    b.Property<int?>("QuantidadeDerrotasParaEliminacao")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade_derrotas_para_eliminacao");

                    b.Property<int?>("QuantidadeGrupos")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade_grupos");

                    b.Property<string>("TipoChave")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tipo_chave");

                    b.Property<int>("TipoFormato")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_formato");

                    b.Property<bool>("TurnoEVolta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("turno_e_volta");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("formatos_campeonato", (string)null);
                });

            modelBuilder.Entity("PlataformaFutevolei.Dominio.Entidades.GrupoAtleta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AtletaId")
                        .HasColumnType("uuid")
                        .HasColumnName("atleta_id");

                    b.Property<Guid>("CompeticaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("competicao_id");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.HasKey("Id");

                    b.HasIndex("AtletaId");

                    b.HasIndex("CompeticaoId");

                    b.HasIndex("CompeticaoId", "AtletaId")
                        .IsUnique();

                    b.ToTable("grupos_atletas", (string)null);
                });

            modelBuilder.Entity("PlataformaFutevolei.Dominio.Entidades.InscricaoCampeonato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CategoriaCompeticaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("categoria_competicao_id");

                    b.Property<Guid>("CompeticaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("competicao_id");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<DateTime>("DataInscricaoUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_inscricao_utc");

                    b.Property<Guid>("DuplaId")
                        .HasColumnType("uuid")
                        .HasColumnName("dupla_id");

                    b.Property<string>("Observacao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("observacao");

                    b.Property<bool>("Pago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("pago");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaCompeticaoId");

                    b.HasIndex("CompeticaoId");

                    b.HasIndex("DuplaId");

                    b.HasIndex("CategoriaCompeticaoId", "DuplaId")
                        .IsUnique();

                    b.ToTable("inscricoes_campeonato", (string)null);
                });

            modelBuilder.Entity("PlataformaFutevolei.Dominio.Entidades.Liga", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("ligas", (string)null);
                });

            modelBuilder.Entity("PlataformaFutevolei.Dominio.Entidades.Local", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<int>("QuantidadeQuadras")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade_quadras");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.Property<Guid?>("UsuarioCriadorId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_criador_id");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.HasIndex("UsuarioCriadorId");

                    b.ToTable("locais", (string)null);
                });

            modelBuilder.Entity("PlataformaFutevolei.Dominio.Entidades.Partida", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativa");

                    b.Property<Guid>("CategoriaCompeticaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("categoria_competicao_id");

                    b.Property<Guid?>("CriadoPorUsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("criado_por_usuario_id");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<DateTime?>("DataPartida")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_partida");

                    b.Property<Guid?>("DuplaAId")
                        .HasColumnType("uuid")
                        .HasColumnName("dupla_a_id");

                    b.Property<Guid?>("DuplaBId")
                        .HasColumnType("uuid")
                        .HasColumnName("dupla_b_id");

                    b.Property<Guid?>("DuplaVencedoraId")
                        .HasColumnType("uuid")
                        .HasColumnName("dupla_vencedora_id");

                    b.Property<bool>("EhFinal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("eh_final");

                    b.Property<bool>("EhFinalissima")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("eh_finalissima");

                    b.Property<bool>("EhPreliminar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("eh_preliminar");

                    b.Property<string>("FaseCampeonato")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("fase_campeonato");

                    b.Property<int?>("LadoDaChave")
                        .HasColumnType("integer")
                        .HasColumnName("lado_da_chave");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("observacoes");

                    b.Property<int?>("OrigemParticipanteATipo")
                        .HasColumnType("integer")
                        .HasColumnName("origem_participante_a_tipo");

                    b.Property<int?>("OrigemParticipanteBTipo")
                        .HasColumnType("integer")
                        .HasColumnName("origem_participante_b_tipo");

                    b.Property<Guid?>("PartidaOrigemParticipanteAId")
                        .HasColumnType("uuid")
                        .HasColumnName("partida_origem_participante_a_id");

                    b.Property<Guid?>("PartidaOrigemParticipanteBId")
                        .HasColumnType("uuid")
                        .HasColumnName("partida_origem_participante_b_id");

                    b.Property<int>("PlacarDuplaA")
                        .HasColumnType("integer")
                        .HasColumnName("placar_dupla_a");

                    b.Property<int>("PlacarDuplaB")
                        .HasColumnType("integer")
                        .HasColumnName("placar_dupla_b");

                    b.Property<int?>("PosicaoNaChave")
                        .HasColumnType("integer")
                        .HasColumnName("posicao_na_chave");

                    b.Property<Guid?>("ProximaPartidaPerdedorId")
                        .HasColumnType("uuid")
                        .HasColumnName("proxima_partida_perdedor_id");

                    b.Property<Guid?>("ProximaPartidaVencedorId")
                        .HasColumnType("uuid")
                        .HasColumnName("proxima_partida_vencedor_id");

                    b.Property<int?>("Rodada")
                        .HasColumnType("integer")
                        .HasColumnName("rodada");

                    b.Property<int?>("SlotDestinoPerdedor")
                        .HasColumnType("integer")
                        .HasColumnName("slot_destino_perdedor");

                    b.Property<int?>("SlotDestinoVencedor")
                        .HasColumnType("integer")
                        .HasColumnName("slot_destino_vencedor");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("status");

                    b.Property<int>("StatusAprovacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3)
                        .HasColumnName("status_aprovacao");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaCompeticaoId");

                    b.HasIndex("CriadoPorUsuarioId");

                    b.HasIndex("DuplaAId");

                    b.HasIndex("DuplaBId");

                    b.HasIndex("DuplaVencedoraId");

                    b.HasIndex("LadoDaChave");

                    b.HasIndex("PartidaOrigemParticipanteAId");

                    b.HasIndex("PartidaOrigemParticipanteBId");

                    b.HasIndex("ProximaPartidaPerdedorId");

                    b.HasIndex("ProximaPartidaVencedorId");

                    b.HasIndex("StatusAprovacao");

                    b.HasIndex("CategoriaCompeticaoId", "DataPartida");

                    b.ToTable("partidas", null, t =>
                        {
                            t.HasCheckConstraint("ck_partidas_duplas_diferentes", "\"dupla_a_id\" IS NULL OR \"dupla_b_id\" IS NULL OR \"dupla_a_id\" <> \"dupla_b_id\"");

                            t.HasCheckConstraint("ck_partidas_placar_nao_negativo", "\"placar_dupla_a\" >= 0 AND \"placar_dupla_b\" >= 0");

                            t.HasCheckConstraint("ck_partidas_status_e_resultado", "((\"status\" = 1) AND \"dupla_vencedora_id\" IS NULL AND \"placar_dupla_a\" = 0 AND \"placar_dupla_b\" = 0) OR ((\"status\" = 2) AND \"dupla_a_id\" IS NOT NULL AND \"dupla_b_id\" IS NOT NULL AND (((\"placar_dupla_a\" = \"placar_dupla_b\") AND \"dupla_vencedora_id\" IS NULL) OR ((\"placar_dupla_a\" > \"placar_dupla_b\") AND \"dupla_vencedora_id\" = \"dupla_a_id\") OR ((\"placar_dupla_b\" > \"placar_dupla_a\") AND \"dupla_vencedora_id\" = \"dupla_b_id\")))");

                            t.HasCheckConstraint("ck_partidas_vencedora_valida", "\"dupla_vencedora_id\" IS NULL OR (\"dupla_a_id\" IS NOT NULL AND \"dupla_b_id\" IS NOT NULL AND (\"dupla_vencedora_id\" = \"dupla_a_id\" OR \"dupla_vencedora_id\" = \"dupla_b_id\"))");
                        });
                });

            modelBuilder.Entity("PlataformaFutevolei.Dominio.Entidades.PartidaAprovacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AtletaId")
                        .HasColumnType("uuid")
                        .HasColumnName("atleta_id");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<DateTime?>("DataResposta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_resposta");

                    b.Property<DateTime>("DataSolicitacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_solicitacao");

                    b.Property<string>("Observacao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("observacao");

                    b.Property<Guid>("PartidaId")
                        .HasColumnType("uuid")
                        .HasColumnName("partida_id");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("status");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("AtletaId");

                    b.HasIndex("PartidaId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("PartidaId", "AtletaId")
                        .IsUnique();

                    b.ToTable("partidas_aprovacoes", (string)null);
                });

            modelBuilder.Entity("PlataformaFutevolei.Dominio.Entidades.PendenciaUsuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AtletaId")
                        .HasColumnType("uuid")
                        .HasColumnName("atleta_id");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_conclusao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<string>("Observacao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("observacao");

                    b.Property<Guid?>("PartidaId")
                        .HasColumnType("uuid")
                        .HasColumnName("partida_id");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("status");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("AtletaId");

                    b.HasIndex("PartidaId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("UsuarioId", "Status");

                    b.ToTable("pendencias_usuarios", (string)null);
                });

            modelBuilder.Entity("PlataformaFutevolei.Dominio.Entidades.RegraCompeticao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("descricao");

                    b.Property<int>("DiferencaMinimaPartida")
                        .HasColumnType("integer")
                        .HasColumnName("diferenca_minima_partida");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<bool>("PermiteEmpate")
                        .HasColumnType("boolean")
                        .HasColumnName("permite_empate");

                    b.Property<decimal>("PontosDerrota")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("pontos_derrota");

                    b.Property<int>("PontosMinimosPartida")
                        .HasColumnType("integer")
                        .HasColumnName("pontos_minimos_partida");

                    b.Property<decimal>("PontosParticipacao")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("pontos_participacao");

                    b.Property<decimal>("PontosPrimeiroLugar")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("pontos_primeiro_lugar");

                    b.Property<decimal>("PontosSegundoLugar")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("pontos_segundo_lugar");

                    b.Property<decimal>("PontosTerceiroLugar")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("pontos_terceiro_lugar");

                    b.Property<decimal>("PontosVitoria")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("pontos_vitoria");

                    b.Property<Guid?>("UsuarioCriadorId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_criador_id");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.HasIndex("UsuarioCriadorId");

                    b.ToTable("regras_competicao", (string)null);
                });

            modelBuilder.Entity("PlataformaFutevolei.Dominio.Entidades.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<Guid?>("AtletaId")
                        .HasColumnType("uuid")
                        .HasColumnName("atleta_id");

                    b.Property<DateTime?>("CodigoLoginExpiraEmUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("codigo_login_expira_em_utc");

                    b.Property<string>("CodigoLoginHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("codigo_login_hash");

                    b.Property<DateTime?>("CodigoRedefinicaoSenhaExpiraEmUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("codigo_redefinicao_senha_expira_em_utc");

                    b.Property<string>("CodigoRedefinicaoSenhaHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("codigo_redefinicao_senha_hash");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<int>("Perfil")
                        .HasColumnType("integer")
                        .HasColumnName("perfil");

                    b.Property<DateTime?>("RefreshTokenExpiraEmUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_token_expira_em_utc");

                    b.Property<string>("RefreshTokenHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("refresh_token_hash");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("senha_hash");

                    b.HasKey("Id");

                    b.HasIndex("AtletaId")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("PlataformaFutevolei.Dominio.Entidades.CategoriaCompeticao", b =>
                {
                    b.HasOne("PlataformaFutevolei.Dominio.Entidades.Competicao", "Competicao")
                        .WithMany("Categorias")
                        .HasForeignKey("CompeticaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlataformaFutevolei.Dominio.Entidades.FormatoCampeonato", "FormatoCampeonato")
                        .WithMany()
                        .HasForeignKey("FormatoCampeonatoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Competicao");

                    b.Navigation("FormatoCampeonato");
                });

            modelBuilder.Entity("PlataformaFutevolei.Dominio.Entidades.Competicao", b =>
                {
                    b.HasOne("PlataformaFutevolei.Dominio.Entidades.FormatoCampeonato", "FormatoCampeonato")
                        .WithMany()
                        .HasForeignKey("FormatoCampeonatoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PlataformaFutevolei.Dominio.Entidades.Liga", "Liga")
                        .WithMany("Competicoes")
                        .HasForeignKey("LigaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PlataformaFutevolei.Dominio.Entidades.Local", "Local")
                        .WithMany("Competicoes")
                        .HasForeignKey("LocalId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PlataformaFutevolei.Dominio.Entidades.RegraCompeticao", "RegraCompeticao")
                        .WithMany("Competicoes")
                        .HasForeignKey("RegraCompeticaoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PlataformaFutevolei.Dominio.Entidades.Usuario", "UsuarioOrganizador")
                        .WithMany()
                        .HasForeignKey("UsuarioOrganizadorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("FormatoCampeonato");

                    b.Navigation("Liga");

                    b.Navigation("Local");

                    b.Navigation("RegraCompeticao");

                    b.Navigation("UsuarioOrganizador");
                });

            modelBuilder.Entity("PlataformaFutevolei.Dominio.Entidades.ConviteCadastro", b =>
                {
                    b.HasOne("PlataformaFutevolei.Dominio.Entidades.Usuario", "CriadoPorUsuario")
                        .WithMany()
                        .HasForeignKey("CriadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CriadoPorUsuario");
                });

            modelBuilder.Entity("PlataformaFutevolei.Dominio.Entidades.Dupla", b =>
                {
                    b.HasOne("PlataformaFutevolei.Dominio.Entidades.Atleta", "Atleta1")
                        .WithMany("DuplasComoAtleta1")
                        .HasForeignKey("Atleta1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PlataformaFutevolei.Dominio.Entidades.Atleta", "Atleta2")
                        .WithMany("DuplasComoAtleta2")
                        .HasForeignKey("Atleta2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Atleta1");

                    b.Navigation("Atleta2");
                });

            modelBuilder.Entity("PlataformaFutevolei.Dominio.Entidades.GrupoAtleta", b =>
                {
                    b.HasOne("PlataformaFutevolei.Dominio.Entidades.Atleta", "Atleta")
                        .WithMany("Grupos")
                        .HasForeignKey("AtletaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PlataformaFutevolei.Dominio.Entidades.Competicao", "Competicao")
                        .WithMany("GrupoAtletas")
                        .HasForeignKey("CompeticaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atleta");

                    b.Navigation("Competicao");
                });

            modelBuilder.Entity("PlataformaFutevolei.Dominio.Entidades.InscricaoCampeonato", b =>
                {
                    b.HasOne("PlataformaFutevolei.Dominio.Entidades.CategoriaCompeticao", "CategoriaCompeticao")
                        .WithMany("Inscricoes")
                        .HasForeignKey("CategoriaCompeticaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlataformaFutevolei.Dominio.Entidades.Competicao", "Competicao")
                        .WithMany("Inscricoes")
                        .HasForeignKey("CompeticaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlataformaFutevolei.Dominio.Entidades.Dupla", "Dupla")
                        .WithMany()
                        .HasForeignKey("DuplaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CategoriaCompeticao");

                    b.Navigation("Competicao");

                    b.Navigation("Dupla");
                });

            modelBuilder.Entity("PlataformaFutevolei.Dominio.Entidades.Local", b =>
                {
                    b.HasOne("PlataformaFutevolei.Dominio.Entidades.Usuario", "UsuarioCriador")
                        .WithMany()
                        .HasForeignKey("UsuarioCriadorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("UsuarioCriador");
                });

            modelBuilder.Entity("PlataformaFutevolei.Dominio.Entidades.Partida", b =>
                {
                    b.HasOne("PlataformaFutevolei.Dominio.Entidades.CategoriaCompeticao", "CategoriaCompeticao")
                        .WithMany("Partidas")
                        .HasForeignKey("CategoriaCompeticaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlataformaFutevolei.Dominio.Entidades.Usuario", "CriadoPorUsuario")
                        .WithMany()
                        .HasForeignKey("CriadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PlataformaFutevolei.Dominio.Entidades.Dupla", "DuplaA")
                        .WithMany("PartidasComoDuplaA")
                        .HasForeignKey("DuplaAId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PlataformaFutevolei.Dominio.Entidades.Dupla", "DuplaB")
                        .WithMany("PartidasComoDuplaB")
                        .HasForeignKey("DuplaBId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PlataformaFutevolei.Dominio.Entidades.Dupla", "DuplaVencedora")
                        .WithMany("PartidasVencidas")
                        .HasForeignKey("DuplaVencedoraId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CategoriaCompeticao");

                    b.Navigation("CriadoPorUsuario");

                    b.Navigation("DuplaA");

                    b.Navigation("DuplaB");

                    b.Navigation("DuplaVencedora");
                });

            modelBuilder.Entity("PlataformaFutevolei.Dominio.Entidades.PartidaAprovacao", b =>
                {
                    b.HasOne("PlataformaFutevolei.Dominio.Entidades.Atleta", "Atleta")
                        .WithMany()
                        .HasForeignKey("AtletaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PlataformaFutevolei.Dominio.Entidades.Partida", "Partida")
                        .WithMany("Aprovacoes")
                        .HasForeignKey("PartidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlataformaFutevolei.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Atleta");

                    b.Navigation("Partida");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PlataformaFutevolei.Dominio.Entidades.PendenciaUsuario", b =>
                {
                    b.HasOne("PlataformaFutevolei.Dominio.Entidades.Atleta", "Atleta")
                        .WithMany()
                        .HasForeignKey("AtletaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PlataformaFutevolei.Dominio.Entidades.Partida", "Partida")
                        .WithMany("Pendencias")
                        .HasForeignKey("PartidaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PlataformaFutevolei.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atleta");

                    b.Navigation("Partida");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PlataformaFutevolei.Dominio.Entidades.RegraCompeticao", b =>
                {
                    b.HasOne("PlataformaFutevolei.Dominio.Entidades.Usuario", "UsuarioCriador")
                        .WithMany()
                        .HasForeignKey("UsuarioCriadorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("UsuarioCriador");
                });

            modelBuilder.Entity("PlataformaFutevolei.Dominio.Entidades.Usuario", b =>
                {
                    b.HasOne("PlataformaFutevolei.Dominio.Entidades.Atleta", "Atleta")
                        .WithOne("Usuario")
                        .HasForeignKey("PlataformaFutevolei.Dominio.Entidades.Usuario", "AtletaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Atleta");
                });

            modelBuilder.Entity("PlataformaFutevolei.Dominio.Entidades.Atleta", b =>
                {
                    b.Navigation("DuplasComoAtleta1");

                    b.Navigation("DuplasComoAtleta2");

                    b.Navigation("Grupos");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PlataformaFutevolei.Dominio.Entidades.CategoriaCompeticao", b =>
                {
                    b.Navigation("Inscricoes");

                    b.Navigation("Partidas");
                });

            modelBuilder.Entity("PlataformaFutevolei.Dominio.Entidades.Competicao", b =>
                {
                    b.Navigation("Categorias");

                    b.Navigation("GrupoAtletas");

                    b.Navigation("Inscricoes");
                });

            modelBuilder.Entity("PlataformaFutevolei.Dominio.Entidades.Dupla", b =>
                {
                    b.Navigation("PartidasComoDuplaA");

                    b.Navigation("PartidasComoDuplaB");

                    b.Navigation("PartidasVencidas");
                });

            modelBuilder.Entity("PlataformaFutevolei.Dominio.Entidades.Liga", b =>
                {
                    b.Navigation("Competicoes");
                });

            modelBuilder.Entity("PlataformaFutevolei.Dominio.Entidades.Local", b =>
                {
                    b.Navigation("Competicoes");
                });

            modelBuilder.Entity("PlataformaFutevolei.Dominio.Entidades.Partida", b =>
                {
                    b.Navigation("Aprovacoes");

                    b.Navigation("Pendencias");
                });

            modelBuilder.Entity("PlataformaFutevolei.Dominio.Entidades.RegraCompeticao", b =>
                {
                    b.Navigation("Competicoes");
                });
#pragma warning restore 612, 618
        }
    }
}
